# http://www.nokogiri.org/tutorials/searching_a_xml_html_document.html
require 'nokogiri'
require 'iconv'
puts "Running jira xml reader."

def only_valid_chars(text)
  return "" unless text
  text
  File.open('entities.xml') do |f|
  #  this removes bad control characters
  text = Iconv.conv('UTF-8//IGNORE', 'UTF-8', f.read.gsub(/[\u0001-\u001A]/ , ''))
  end

  text.encode('UTF-8', 'UTF-8', {:invalid => :replace, :undef => :replace, :replace => ""})
  
  return text
end

@doc = Nokogiri::XML(only_valid_chars(File.open("entities.xml")))
#run this to check that whole document reads
# puts @doc.xpath("*")

#list project names
puts "Available Projects:"
projectlist= @doc.xpath("//Project/@name")
# //Project/@name
# type: Nokogiri::XML::NodeSet
for item in projectlist
    puts item
end

# projectlist.xpath("/@nam").each do |node|
#   # some instruction
# end


puts projectlist.class.name.to_s
puts projectlist[0].to_s

# projectlist1="sup"
# print projectlist1
# puts @doc.css("Project name")
# //Project[@name]
# @name
#select project or do all projects w/ 4 loop
projectname="TAIGA JIRA IMPORTER"
# get specific project
puts @doc.xpath("//Project[@name='"+projectname+"']")
# [@lang='en']

puts "selected project: "+projectname

# "Some string \u000F more".gsub(/[\u0001-\u001A]/ , '')
# puts @doc.xpath("//AuditChangedValue")


# puts "Running jira xml reader."
# #list jira projects

# #get project name
# puts "Give project name"

# projectName=""
# get project info
# get project objects
# @doc = Nokogiri::XML(File.open("entities.xml"))
# Project

# //@name
# problem at: OSPropertyText
# value here has the problem
# <OSPropertyString id="12559">
#         <value><![CDATA[#java.util.Map
# openIssuesActionignore
# releaseDate31/Oct/16
# buildTypeno-build
# username]]></value>
#     </OSPropertyString>
#     <OSPropertyString id="12560">
#         <value><![CDATA[#java.util.Map
# openIssuesActionignore
# releaseDate31/Oct/16
# buildTypeno-build
# username]]></value>
#     </OSPropertyString>
# Unicode: 0xc looks like FF

# wont do this <OSPropertyString id="12560">
# not working: OSWorkflowEntry
#working paths:
# AuditItem Avatar ChangeItem newstring ConfigurationContext EventType OSPropertyEntry OSPropertyNumber
# OSPropertyString value descriptor


# puts (@doc.xpath("//Project")).to_s
# puts "candy"
# http://www.w3schools.com/xml/xpath_syntax.asp

# print
#database schema https://developer.atlassian.com/jiradev/jira-platform/jira-architecture/database-schema
# ar_tires = @doc.xpath('//car:tire', 'car' => 'http://alicesautoparts.com/')
#convert to taiga json
    # <Project id="10119" name="TAIGA JIRA IMPORTER" url="https://tree.taiga.io/project/last_link-taiga-jira-importer/backlog" lead="theefunk" description="build a parser to convert jira xml to taiga and taiga json to jira xml." key="TJI" counter="10" assigneetype="3" avatar="10510" originalkey="TJI" projecttype="software"/>

# <AuditChangedValue id="10737" logId="10492" name="Name" deltaTo="Software Simplified Workflow for Project TJI"/>
#     <AuditChangedValue id="10738" logId="10492" name="Description" deltaTo="Generated by JIRA Software version 7.2.8-DAILY20160816152029. This workflow is managed internally by JIRA Software. Do not manually modify this workflow."/>
#     <AuditChangedValue id="10739" logId="10493" name="Name" deltaTo="TJI: Software Simplified Workflow Scheme"/>
#     <AuditChangedValue id="10740" logId="10493" name="Description" deltaTo="Generated by JIRA Software version 7.2.8-DAILY20160816152029. This workflow scheme is managed internally by JIRA Software. Do not manually modify this workflow scheme."/>
#     <AuditChangedValue id="10741" logId="10497" name="Name" deltaTo="TAIGA JIRA IMPORTER"/>
#     <AuditChangedValue id="10742" logId="10497" name="Key" deltaTo="TJI"/>
#     <AuditChangedValue id="10743" logId="10497" name="Description" deltaTo=""/>
#     <AuditChangedValue id="10744" logId="10497" name="URL" deltaTo=""/>
#     <AuditChangedValue id="10745" logId="10497" name="Project Lead" deltaTo="username"/>
#     <AuditChangedValue id="10746" logId="10497" name="Default Assignee" deltaTo="Unassigned"/>
#     <AuditChangedValue id="10747" logId="10498" name="Description" deltaFrom="" deltaTo="build a parser to convert jira xml to taiga and taiga json to jira xml."/>
#     <AuditChangedValue id="10748" logId="10498" name="URL" deltaFrom="" deltaTo="https://tree.taiga.io/project/last_link-taiga-jira-importer/backlog"/>
#     <AuditChangedValue id="10749" logId="10500" name="Name" deltaTo="Version One"/>
#     <AuditChangedValue id="10750" logId="10500" name="Description" deltaTo="finish exporter v1"/>
#     <AuditChangedValue id="10751" logId="10500" name="Release date" deltaTo="2016-12-10"/>
#     <AuditChangedValue id="10752" logId="10501" name="Name" deltaTo="jira data"/>
#     <AuditChangedValue id="10753" logId="10501" name="Description" deltaTo="test component"/>
#     <AuditChangedValue id="10754" logId="10501" name="Component Lead" deltaTo="username"/>
#     <AuditChangedValue id="10755" logId="10501" name="Default Assignee" deltaTo="Component Lead"/>
#     <AuditChangedValue id="10756" logId="10502" name="Name" deltaTo="Completed Version"/>
#     <AuditChangedValue id="10757" logId="10502" name="Description" deltaTo="test completion"/>
#     <AuditChangedValue id="10758" logId="10502" name="Release date" deltaTo="2016-10-31"/>
#     <AuditChangedValue id="10759" logId="10504" name="Name" deltaTo="test Comp"/>
#     <AuditChangedValue id="10760" logId="10504" name="Default Assignee" deltaTo="Project Default"/>